//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchebka123k4s1.Data.Remote.SqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSize
    {
        public int Id { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual SizeUnit SizeUnit { get; set; }
    }
}
